services:
  webserver:
    image: ghcr.io/jonilive/webserver:latest
    container_name: webserver
    ports:
      - "80:80"
    volumes:
      - ./appdata/config:/var/config
      - ./appdata/log:/var/log
      - ./appdata/www:/www
    restart: unless-stopped
